#!/bin/bash
source "$HOME/.config/colors/colors.sh"

options=(
	style=uniform
	width=5
	hidpi=on
	#inactive_color="${BACKGROUND}"
	active_color="${ACCENT_SECONDARY}"
	blacklist=""
)

borders "${options[@]}"
