#!/bin/bash
source "$HOME/.config/colors/colors.sh"

options=(
	style=rounded
	width=2.5
	hidpi=on
	inactive_color="${BACKGROUND}"
	active_color="${ACCENT_SECONDARY}"
	blacklist="Arc,Windows App"
	order=above
)

borders "${options[@]}"
