#!/bin/bash
source "$HOME/.config/colors/colors.sh"

options=(
	style=uniform
	width=7.5
	hidpi=on
	#inactive_color=0x90222726
	active_color="${ACCENT_SECONDARY}"
	blacklist="kitty"
)

borders "${options[@]}"
