# maps
map ctrl+b launch --type=overlay zsh -ic "cq"
map ctrl+a launch --type=overlay zsh -ic "win"

allow_remote_control yes

font_family Menlo
font_size 16
disable_ligatures never

# Layout
remember_window_position no
remember_window_size no
window_padding_width 18
initial_window_width 500
initial_window_height 280

# Window chrome
hide_window_decorations titlebar-only
confirm_os_window_close 0

# Background
background_opacity 0.75
background_blur 100

# Cursor
cursor_shape block
cursor_blink_interval 0

